"use strict";
exports.__esModule = true;
exports.spotify = exports.docker = exports.c = exports.rust = exports.mui = exports.jest = exports.npm = exports.gatsby = exports.scss = exports.nginx = exports.aws = exports.nestjs = exports.java = exports.postgres = exports.mongodb = exports.typescript = exports.react = exports.css = exports.nodeJs = void 0;
exports.nodeJs = "#539E43";
exports.css = "#264de4";
exports.react = "#61dbfb";
exports.typescript = "#007acc";
exports.mongodb = "#4db33d";
exports.postgres = "#008bb9";
exports.java = "#ed8b00";
exports.nestjs = "#E0234E";
exports.aws = "#FF9900";
exports.nginx = "#009900";
exports.scss = "#c69";
exports.gatsby = "#663399";
exports.npm = "#CB3837";
exports.jest = "#C63D14";
exports.mui = "#007FFF";
exports.rust = "#F74C00";
exports.c = "#283593";
exports.docker = "#1D63ED";
exports.spotify = "#1db954";
